const COLORS={H:'#f8fbff',O:'#ff2e43',N:'#3367ff',F:'#42e64c',Cl:'#22c95c',Na:'#9667ff'};
const MOLECULES={Hplus:{atoms:[{id:'H',e:'H',p:[0,0,0],r:.28,charge:'+'}],bonds:[]},H2O:{atoms:[{id:'O',e:'O',p:[0,0,0],r:.32},{id:'H1',e:'H',p:[-.72,.58,0],r:.20},{id:'H2',e:'H',p:[.72,.58,0],r:.20}],bonds:[['O','H1'],['O','H2']]},H3O:{atoms:[{id:'O',e:'O',p:[0,.05,-.18],r:.33,charge:'+'},{id:'H1',e:'H',p:[.78,.18,.28],r:.20},{id:'H2',e:'H',p:[-.40,.72,.28],r:.20},{id:'H3',e:'H',p:[-.40,-.55,.28],r:.20}],bonds:[['O','H1'],['O','H2'],['O','H3']]},OH:{atoms:[{id:'O',e:'O',p:[-.28,0,0],r:.33,charge:'−'},{id:'H',e:'H',p:[.64,0,0],r:.20}],bonds:[['O','H']]},HF:{atoms:[{id:'H',e:'H',p:[-.48,0,0],r:.20},{id:'F',e:'F',p:[.43,0,0],r:.35}],bonds:[['H','F']]},F:{atoms:[{id:'F',e:'F',p:[0,0,0],r:.38,charge:'−'}],bonds:[]},Na:{atoms:[{id:'Na',e:'Na',p:[0,0,0],r:.40,charge:'+'}],bonds:[]},Cl:{atoms:[{id:'Cl',e:'Cl',p:[0,0,0],r:.43,charge:'−'}],bonds:[]},NH3:{atoms:[{id:'N',e:'N',p:[0,.03,-.22],r:.34},{id:'H1',e:'H',p:[.80,.10,.30],r:.20},{id:'H2',e:'H',p:[-.40,.72,.30],r:.20},{id:'H3',e:'H',p:[-.40,-.58,.30],r:.20}],bonds:[['N','H1'],['N','H2'],['N','H3']]},NH4:{atoms:[{id:'N',e:'N',p:[0,0,0],r:.34,charge:'+'},{id:'H1',e:'H',p:[.62,.62,.62],r:.20},{id:'H2',e:'H',p:[-.62,-.62,.62],r:.20},{id:'H3',e:'H',p:[-.62,.62,-.62],r:.20},{id:'H4',e:'H',p:[.62,-.62,-.62],r:.20}],bonds:[['N','H1'],['N','H2'],['N','H3'],['N','H4']]}};
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function hexToRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255];}function mix(rgb,toward,t){return rgb.map((v,i)=>Math.round(v+(toward[i]-v)*t));}function rgbString(v){return`rgb(${v[0]}, ${v[1]}, ${v[2]})`;}
function rotate([x,y,z],[rx,ry,rz]){let cy=Math.cos(rx),sy=Math.sin(rx),y1=y*cy-z*sy,z1=y*sy+z*cy,x1=x;cy=Math.cos(ry);sy=Math.sin(ry);let x2=x1*cy+z1*sy,z2=-x1*sy+z1*cy,y2=y1;cy=Math.cos(rz);sy=Math.sin(rz);return[x2*cy-y2*sy,x2*sy+y2*cy,z2];}
function projectedAtom(atom,origin,scale,rotation,globalZ=0){const r=rotate(atom.p,rotation),depth=clamp(globalZ+r[2]*.35,-1.4,1.4),persp=1/(1+depth*.12);return{...atom,x:origin.x+r[0]*scale*persp,y:origin.y+r[1]*scale*persp,z:depth,radius:atom.r*scale*persp};}
function drawBond(ctx,a,b){const dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1,nx=-dy/length,ny=dx/length,width=Math.max(3,Math.min(a.radius,b.radius)*.52),grad=ctx.createLinearGradient((a.x+b.x)/2+nx*width,(a.y+b.y)/2+ny*width,(a.x+b.x)/2-nx*width,(a.y+b.y)/2-ny*width);grad.addColorStop(0,'#f7fbff');grad.addColorStop(.22,'#b8c5ce');grad.addColorStop(.65,'#707d87');grad.addColorStop(1,'#3e4a52');ctx.save();ctx.lineCap='round';ctx.strokeStyle='rgba(43,55,63,.32)';ctx.lineWidth=width+2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle=grad;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore();}
function drawAtom(ctx,atom,alpha=1){const rgb=hexToRgb(COLORS[atom.e]||'#999999'),light=mix(rgb,[255,255,255],atom.e==='H' ? 0.78 : 0.48),dark=mix(rgb,[0,0,0],atom.e==='H' ? 0.22 : 0.38),r=atom.radius,grad=ctx.createRadialGradient(atom.x-r*.38,atom.y-r*.42,Math.max(1,r*.05),atom.x,atom.y,r);grad.addColorStop(0,'rgba(255,255,255,.98)');grad.addColorStop(.16,rgbString(light));grad.addColorStop(.50,rgbString(rgb));grad.addColorStop(1,rgbString(dark));ctx.save();ctx.globalAlpha*=alpha;ctx.shadowColor='rgba(12,31,43,.28)';ctx.shadowBlur=r*.35;ctx.shadowOffsetY=r*.12;ctx.fillStyle=grad;ctx.beginPath();ctx.arc(atom.x,atom.y,r,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(15,29,36,.22)';ctx.lineWidth=Math.max(.8,r*.055);ctx.stroke();if(atom.charge){ctx.fillStyle=atom.e==='H'?'#17222b':'#fff';ctx.font=`900 ${Math.max(10,r*.82)}px ui-sans-serif, system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(atom.charge,atom.x,atom.y+.5);}ctx.restore();}
export function drawMolecule3D(ctx,kind,origin,scale,rotation=[0,0,0],globalZ=0,alpha=1){const def=MOLECULES[kind]||MOLECULES.H2O,atoms=def.atoms.map(a=>projectedAtom(a,origin,scale,rotation,globalZ)),map=Object.fromEntries(atoms.map(a=>[a.id,a])),bonds=def.bonds.map(([a,b])=>[map[a],map[b]]).sort((x,y)=>(y[0].z+y[1].z)-(x[0].z+x[1].z));ctx.save();ctx.globalAlpha*=alpha;for(const[a,b]of bonds)drawBond(ctx,a,b);atoms.sort((a,b)=>b.z-a.z).forEach(a=>drawAtom(ctx,a));ctx.restore();}
export function drawProton(ctx,x,y,radius=8,alpha=1){drawAtom(ctx,{e:'H',x,y,radius,charge:'+'},alpha);}export function moleculeLabel(kind){return({Hplus:'H⁺',H2O:'H₂O',H3O:'H₃O⁺',OH:'OH⁻',HF:'HF',F:'F⁻',Na:'Na⁺',Cl:'Cl⁻',NH3:'NH₃',NH4:'NH₄⁺'})[kind]||kind;}
