import { drawMolecule3D, drawProton, moleculeLabel } from './molecule-3d.js';
import { stageForState } from '../instructional-model.js';

const NEUTRALIZATION = {
  'strong-acid': { reactants: ['Hplus','OH'], products: ['H2O'], equation: 'H⁺ + OH⁻ → H₂O', donor: 0, acceptor: 1 },
  'weak-acid': { reactants: ['HF','OH'], products: ['F','H2O'], equation: 'HF + OH⁻ → F⁻ + H₂O', donor: 0, acceptor: 1 },
  'weak-base': { reactants: ['NH3','Hplus'], products: ['NH4'], equation: 'NH₃ + H⁺ → NH₄⁺', donor: 1, acceptor: 0 }
};
const EQUIVALENCE_EQUILIBRIA = {
  'weak-acid': { equation: 'F⁻ + H₂O ⇌ HF + OH⁻', forward: { reactants: ['F','H2O'], products: ['HF','OH'], donor: 1, acceptor: 0, name: 'F⁻ hydrolysis' }, reverse: { reactants: ['HF','OH'], products: ['F','H2O'], donor: 0, acceptor: 1, name: 'reverse proton transfer' } },
  'weak-base': { equation: 'NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺', forward: { reactants: ['NH4','H2O'], products: ['NH3','H3O'], donor: 0, acceptor: 1, name: 'NH₄⁺ acid reaction' }, reverse: { reactants: ['NH3','H3O'], products: ['NH4','H2O'], donor: 1, acceptor: 0, name: 'reverse proton transfer' } }
};

export class ReactionCloseupView {
  constructor(root) { this.root=root;this.scenario=null;this.state=null;this.triggerAt=performance.now()-9999;this.frozen=false;this.freezeTime=0;this.renderShell();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(root);this.resize();this.frame=requestAnimationFrame(t=>this.animate(t)); }
  renderShell(){this.root.innerHTML=`<div class="reaction-equation-stack" id="reaction-equation-closeup"></div><div class="reaction-stage-wrap"><canvas class="reaction-canvas" aria-label="Magnified three-dimensional acid-base reaction animation"></canvas><div class="reaction-stage-label" id="reaction-stage-label">Add titrant to animate a proton-transfer event.</div></div>`;this.canvas=this.root.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.equation=this.root.querySelector('#reaction-equation-closeup');this.label=this.root.querySelector('#reaction-stage-label');}
  resize(){const rect=this.root.querySelector('.reaction-stage-wrap').getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(rect.width*dpr));this.canvas.height=Math.max(1,Math.round(rect.height*dpr));this.canvas.style.width=`${rect.width}px`;this.canvas.style.height=`${rect.height}px`;this.dpr=dpr;}
  setFrozen(frozen){if(frozen&&!this.frozen)this.freezeTime=performance.now();this.frozen=Boolean(frozen);}
  setState(scenario,state){this.scenario=scenario;this.state=state;const n=NEUTRALIZATION[scenario.kind],eq=EQUIVALENCE_EQUILIBRIA[scenario.kind],atEquivalence=stageForState(scenario,state)==='equivalence',equilibriumRow=eq&&atEquivalence?`<div class="reaction-equation-row" data-reaction-row="equilibrium"><span>Why equivalence is ${scenario.kind==='weak-acid'?'basic':'acidic'}</span><strong>${eq.equation}</strong></div>`:'';this.equation.innerHTML=`<div class="reaction-equation-row" data-reaction-row="neutralization"><span>Titration reaction</span><strong>${n?.equation||scenario.reaction}</strong></div>${equilibriumRow}`;}
  trigger(){this.triggerAt=performance.now();}
  animate(time){const effectiveTime=this.frozen?this.freezeTime:time;this.draw(effectiveTime);this.frame=requestAnimationFrame(t=>this.animate(t));}
  setActiveEquation(mode){this.root.querySelectorAll('[data-reaction-row]').forEach(row=>row.classList.toggle('active',row.dataset.reactionRow===mode));}
  drawReaction(ctx,reaction,time,progress,{equilibrium=false}={}){const w=this.canvas.width/this.dpr,h=this.canvas.height/this.dpr,scale=Math.max(32,Math.min(55,w*.055)),y=h*.50,leftRest=w*.29,rightRest=w*.71,rotA=[time*.00025,time*.00038,time*.00019],rotB=[time*.00031,-time*.00028,time*.00023],t=Math.max(0,Math.min(1,progress)),approach=Math.min(1,t/.30),transfer=Math.max(0,Math.min(1,(t-.30)/.34)),separate=Math.max(0,Math.min(1,(t-.64)/.36)),leftMeet=w*.43,rightMeet=w*.57,leftX=leftRest+(leftMeet-leftRest)*approach,rightX=rightRest+(rightMeet-rightRest)*approach,productLeftX=leftMeet+(w*.24-leftMeet)*separate,productRightX=rightMeet+(w*.76-rightMeet)*separate,productAlpha=transfer,reactantAlpha=1-transfer;drawMolecule3D(ctx,reaction.reactants[0],{x:leftX,y},scale,rotA,-.1,reactantAlpha);drawMolecule3D(ctx,reaction.reactants[1],{x:rightX,y},scale,rotB,.15,reactantAlpha);if(reaction.products[0])drawMolecule3D(ctx,reaction.products[0],{x:productLeftX,y},scale,rotA,-.1,productAlpha);if(reaction.products[1])drawMolecule3D(ctx,reaction.products[1],{x:productRightX,y},scale,rotB,.15,productAlpha);if(t>.30&&t<.68){const q=(t-.30)/.38,donorX=reaction.donor===0?leftMeet:rightMeet,acceptorX=reaction.acceptor===0?leftMeet:rightMeet,offset=reaction.donor===0?scale*.26:-scale*.26,startX=donorX+offset,endX=acceptorX-offset,arcY=y-Math.sin(q*Math.PI)*scale*.42;drawProton(ctx,startX+(endX-startX)*q,arcY,Math.max(7,scale*.13),Math.sin(q*Math.PI));}if(equilibrium){if(t<.30)this.label.textContent=`${reaction.name}: the equilibrium partners approach.`;else if(t<.68)this.label.textContent=`${reaction.name}: a proton transfers between the conjugate partners and water.`;else this.label.textContent=`${reaction.name}: products separate; the reverse process also occurs.`;}else if(t<.30)this.label.textContent='Reactants approach and adopt a favorable orientation.';else if(t<.68)this.label.textContent='A proton transfers during the acid-base collision.';else this.label.textContent='The reaction products separate; newly formed water blends into the solvent background.';}
  draw(time){if(!this.ctx||!this.scenario||!this.dpr||!this.state)return;const ctx=this.ctx,w=this.canvas.width/this.dpr,h=this.canvas.height/this.dpr;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,w,h);const neutral=NEUTRALIZATION[this.scenario.kind],equilibrium=EQUIVALENCE_EQUILIBRIA[this.scenario.kind],atEquivalence=stageForState(this.scenario,this.state)==='equivalence',neutralAge=time-this.triggerAt;if(!atEquivalence&&neutralAge>=0&&neutralAge<3200){this.setActiveEquation('neutralization');this.drawReaction(ctx,neutral,time,Math.min(1,neutralAge/2800));return;}if(atEquivalence&&equilibrium){this.setActiveEquation('equilibrium');const cycleMs=3900,cycle=Math.floor(time/cycleMs),progress=(time%cycleMs)/cycleMs,reaction=cycle%2===0?equilibrium.forward:equilibrium.reverse;this.drawReaction(ctx,reaction,time,progress,{equilibrium:true});return;}this.setActiveEquation('neutralization');const scale=Math.max(32,Math.min(55,w*.055)),y=h*.50;drawMolecule3D(ctx,neutral.reactants[0],{x:w*.29,y},scale,[time*.00025,time*.00038,time*.00019],-.1,.96);drawMolecule3D(ctx,neutral.reactants[1],{x:w*.71,y},scale,[time*.00031,-time*.00028,time*.00023],.15,.96);if(this.scenario.kind==='weak-acid')this.label.textContent='Before equivalence, focus on HF + OH⁻ → F⁻ + H₂O. The F⁻/water equilibrium becomes the teaching focus at equivalence.';else if(this.scenario.kind==='weak-base')this.label.textContent='Before equivalence, focus on NH₃ + H⁺ → NH₄⁺. The NH₄⁺/water equilibrium becomes the teaching focus at equivalence.';else this.label.textContent=`Magnified reactants: ${moleculeLabel(neutral.reactants[0])} and ${moleculeLabel(neutral.reactants[1])}. Add titrant to replay proton transfer.`;}
}
